#version: '3.9'

networks:
  loomanet:
    external: true

services:
  looma-streamlit:
    # image: ghcr.io/looma/loomadb:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # from host environment
      - QDRANT_URL=http://looma-qdrant:6333
      - MONGO_URI=mongodb://looma-db:27017
      - MONGO_DB=looma
      - DATADIR=/app/data/files
    image: loomaai:latest
    container_name: looma-streamlit
    ports:
      - 47000:4700
    volumes:
      - ./data:/app/data
      - ./appai:/app/appai
    restart: always
    tty: true
    networks:
      - loomanet

  looma-qdrant:
    # image: ghcr.io/looma/loomadb:latest
    image: qdrant/qdrant:latest
    container_name: looma-qdrant
    ports:
      - 46333:6333
    restart: always
    tty: true
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - loomanet