#version: '3.9'

networks:
  loomafront:
    name: loomafront
    external: false
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: loomafront
  loomaainet:

services:
  loomaai:
    # image: ghcr.io/looma/loomadb:latest
    image: loomaai:latest
    container_name: loomaai
    ports:
      - 47000:4700
    volumes:
      - ./data:/app/data
      - ./appai:/app/appai
    restart: always
    tty: true
    networks:
      - loomaainet
      - loomafront

  qdrant:
    # image: ghcr.io/looma/loomadb:latest
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 46333:6333
    restart: always
    tty: true
    networks:
      - loomaainet
      - loomafront