#version: '3.9'

networks:
  loomanet:
    external: true

services:
  looma-streamlit:
    # image: ghcr.io/looma/loomadb:latest
    image: loomaai:latest
    container_name: looma-streamlit
    ports:
      - 47000:4700
    volumes:
      - ./data:/app/data
      - ./appai:/app/appai
    restart: always
    tty: true
    networks:
      - loomanet

  looma-qdrant:
    # image: ghcr.io/looma/loomadb:latest
    image: qdrant/qdrant:latest
    container_name: looma-qdrant
    ports:
      - 46333:6333
    restart: always
    tty: true
    networks:
      - loomanet